{{- if (ne .Values.cluster.useHostNetworking true) -}}
{{- if .Values.cluster.inline }}
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: inline-2
plugin: sriov
 
args: '[
       {
                "if0": "{{ .Values.networkInterfaces.inline2interface.deviceName }}",
                "ipam": {
                  "type": "host-local",
                  "subnet": "10.4.0.0/16",
                  "rangeStart": "10.4.0.10",
                  "rangeEnd": "10.4.0.150"
                }
        }
        ]'
{{- end }}
{{- end -}}