{{- if (ne .Values.cluster.useHostNetworking true) -}}
{{- if .Values.cluster.inline }}
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: inline-1 
plugin: sriov

args: '[
       {
                "if0": "{{ .Values.networkInterfaces.inline1interface.deviceName }}",
                "ipam": {
                  "type": "host-local",
                  "subnet": "10.3.0.0/16",
                  "rangeStart": "10.3.0.10",
                  "rangeEnd": "10.3.0.150"
                }
        }
        ]'
{{- end }}
{{- end -}}