{{- if ne .Values.cluster.useHostNetworking true -}}
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: passive
plugin: sriov

args: '[
       {
                "if0": "{{ .Values.networkInterfaces.passive1interface.deviceName }}",
                "ipam": {
                  "type": "host-local",
                  "subnet": "10.51.0.0/16",
                  "rangeStart": "10.51.0.10",
                  "rangeEnd": "10.51.0.150"
                }
        }
        ]'
{{- end -}}