{{- if .Values.cluster.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: inline-interface1
type: Opaque
data:
  {{- if .Values.cluster.useHostNetworking }}
  interface: {{ .Values.networkInterfaces.inline1interface.deviceName | b64enc | quote }}
  {{- else }}
  interface: {{ "net0" | b64enc | quote }}
  {{- end }}  
  
---
apiVersion: v1
kind: Secret
metadata:
  name: inline-interface2
type: Opaque
data:
  {{- if .Values.cluster.useHostNetworking }}
  interface: {{ .Values.networkInterfaces.inline2interface.deviceName | b64enc | quote }}
  {{- else }}
  interface: {{ "net1" | b64enc | quote }}
  {{- end }}  
  
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: passive-interface
type: Opaque
data:
  {{- if .Values.cluster.useHostNetworking }}
  interface: {{ .Values.networkInterfaces.passive1interface.deviceName | b64enc | quote }}
  {{- else }}
  interface: {{ "net0" | b64enc | quote }}
  {{- end }}  
{{- end }}